#	Especifica la imagen a utilizar como base
FROM node AS builder
#	Ejecuta el commando para crear una carpeta en la ubicación actual
RUN mkdir -p /usr/src/app
#	Especifica la carpeta de trabajo dentro del contenedor. A partir del momento en que se ejecuta esta #instrucción, todos los comandos siguientes se ejecutarán de forma relativa a <ruta>. 
WORKDIR /usr/src/app
#	COPY [--from=<fase>] <origen> <destino> copia los ficheros de <origen> en <destino>. Los 
#	parámetros son relativos al contexto de construcción (la carpeta donde se encuentra Dockerfile):
COPY . /usr/src/app
#	Reconocerá los comandos de node por que ya lo tiene instalado
RUN npm install
#	Compilacion de aplicación.AOT: puede reducir el código innecesario, pre-compilar la #	aplicación para que el navegador cargue la aplicación mucho más rapido y 
#	además podemos detectar problemas en las plantillas antes de que la
#	aplicación corra en el navegador.
RUN $(npm bin)/ng build --prod --aot
FROM nginx
WORKDIR /usr/share/nginx/html/
COPY --from=builder /usr/src/app/dist/64812 Mejia Pacheco-63157 Gasca Farrera/ /usr/share/nginx/html
#	Puertos en los que va a exponer
EXPOSE 80 443
CMD nginx -g 'daemon off;'

